// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asyncrpc.proto

#ifndef PROTOBUF_asyncrpc_2eproto__INCLUDED
#define PROTOBUF_asyncrpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

namespace protobuf_asyncrpc_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void InitDefaultsGenericRequestImpl();
void InitDefaultsGenericRequest();
void InitDefaultsGenericResponseImpl();
void InitDefaultsGenericResponse();
void InitDefaultsGenericErrorResponseImpl();
void InitDefaultsGenericErrorResponse();
inline void InitDefaults() {
  InitDefaultsGenericRequest();
  InitDefaultsGenericResponse();
  InitDefaultsGenericErrorResponse();
}
}  // namespace protobuf_asyncrpc_2eproto
namespace GameWorkstore {
namespace AsyncNetworkEngine {
class GenericErrorResponse;
class GenericErrorResponseDefaultTypeInternal;
extern GenericErrorResponseDefaultTypeInternal _GenericErrorResponse_default_instance_;
class GenericRequest;
class GenericRequestDefaultTypeInternal;
extern GenericRequestDefaultTypeInternal _GenericRequest_default_instance_;
class GenericResponse;
class GenericResponseDefaultTypeInternal;
extern GenericResponseDefaultTypeInternal _GenericResponse_default_instance_;
}  // namespace AsyncNetworkEngine
}  // namespace GameWorkstore
namespace GameWorkstore {
namespace AsyncNetworkEngine {

enum Transmission {
  NotSpecified = 0,
  ErrorConnection = 1,
  ErrorProtocol = 2,
  ErrorParser = 3,
  Success = 200,
  ErrorNoData = 204,
  ErrorDecode = 400,
  ErrorUnauthorized = 401,
  ErrorForbidden = 403,
  ErrorMethodNotAllowed = 405,
  ErrorRequestTimeout = 408,
  ErrorEncode = 421,
  ErrorInternalServer = 500,
  ErrorNotImplemented = 501,
  ErrorNetworkAuthenticationRequired = 511,
  Transmission_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Transmission_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Transmission_IsValid(int value);
const Transmission Transmission_MIN = NotSpecified;
const Transmission Transmission_MAX = ErrorNetworkAuthenticationRequired;
const int Transmission_ARRAYSIZE = Transmission_MAX + 1;

// ===================================================================

class GenericRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:GameWorkstore.AsyncNetworkEngine.GenericRequest) */ {
 public:
  GenericRequest();
  virtual ~GenericRequest();

  GenericRequest(const GenericRequest& from);

  inline GenericRequest& operator=(const GenericRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GenericRequest(GenericRequest&& from) noexcept
    : GenericRequest() {
    *this = ::std::move(from);
  }

  inline GenericRequest& operator=(GenericRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const GenericRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenericRequest* internal_default_instance() {
    return reinterpret_cast<const GenericRequest*>(
               &_GenericRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GenericRequest* other);
  friend void swap(GenericRequest& a, GenericRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GenericRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GenericRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const GenericRequest& from);
  void MergeFrom(const GenericRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GenericRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Messege = 1;
  void clear_messege();
  static const int kMessegeFieldNumber = 1;
  const ::std::string& messege() const;
  void set_messege(const ::std::string& value);
  #if LANG_CXX11
  void set_messege(::std::string&& value);
  #endif
  void set_messege(const char* value);
  void set_messege(const char* value, size_t size);
  ::std::string* mutable_messege();
  ::std::string* release_messege();
  void set_allocated_messege(::std::string* messege);

  // @@protoc_insertion_point(class_scope:GameWorkstore.AsyncNetworkEngine.GenericRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr messege_;
  mutable int _cached_size_;
  friend struct ::protobuf_asyncrpc_2eproto::TableStruct;
  friend void ::protobuf_asyncrpc_2eproto::InitDefaultsGenericRequestImpl();
};
// -------------------------------------------------------------------

class GenericResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:GameWorkstore.AsyncNetworkEngine.GenericResponse) */ {
 public:
  GenericResponse();
  virtual ~GenericResponse();

  GenericResponse(const GenericResponse& from);

  inline GenericResponse& operator=(const GenericResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GenericResponse(GenericResponse&& from) noexcept
    : GenericResponse() {
    *this = ::std::move(from);
  }

  inline GenericResponse& operator=(GenericResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const GenericResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenericResponse* internal_default_instance() {
    return reinterpret_cast<const GenericResponse*>(
               &_GenericResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(GenericResponse* other);
  friend void swap(GenericResponse& a, GenericResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GenericResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GenericResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const GenericResponse& from);
  void MergeFrom(const GenericResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GenericResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Messege = 2;
  void clear_messege();
  static const int kMessegeFieldNumber = 2;
  const ::std::string& messege() const;
  void set_messege(const ::std::string& value);
  #if LANG_CXX11
  void set_messege(::std::string&& value);
  #endif
  void set_messege(const char* value);
  void set_messege(const char* value, size_t size);
  ::std::string* mutable_messege();
  ::std::string* release_messege();
  void set_allocated_messege(::std::string* messege);

  // @@protoc_insertion_point(class_scope:GameWorkstore.AsyncNetworkEngine.GenericResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr messege_;
  mutable int _cached_size_;
  friend struct ::protobuf_asyncrpc_2eproto::TableStruct;
  friend void ::protobuf_asyncrpc_2eproto::InitDefaultsGenericResponseImpl();
};
// -------------------------------------------------------------------

class GenericErrorResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse) */ {
 public:
  GenericErrorResponse();
  virtual ~GenericErrorResponse();

  GenericErrorResponse(const GenericErrorResponse& from);

  inline GenericErrorResponse& operator=(const GenericErrorResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GenericErrorResponse(GenericErrorResponse&& from) noexcept
    : GenericErrorResponse() {
    *this = ::std::move(from);
  }

  inline GenericErrorResponse& operator=(GenericErrorResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const GenericErrorResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenericErrorResponse* internal_default_instance() {
    return reinterpret_cast<const GenericErrorResponse*>(
               &_GenericErrorResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GenericErrorResponse* other);
  friend void swap(GenericErrorResponse& a, GenericErrorResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GenericErrorResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GenericErrorResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const GenericErrorResponse& from);
  void MergeFrom(const GenericErrorResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GenericErrorResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // @@protoc_insertion_point(class_scope:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  mutable int _cached_size_;
  friend struct ::protobuf_asyncrpc_2eproto::TableStruct;
  friend void ::protobuf_asyncrpc_2eproto::InitDefaultsGenericErrorResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GenericRequest

// string Messege = 1;
inline void GenericRequest::clear_messege() {
  messege_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericRequest::messege() const {
  // @@protoc_insertion_point(field_get:GameWorkstore.AsyncNetworkEngine.GenericRequest.Messege)
  return messege_.GetNoArena();
}
inline void GenericRequest::set_messege(const ::std::string& value) {
  
  messege_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameWorkstore.AsyncNetworkEngine.GenericRequest.Messege)
}
#if LANG_CXX11
inline void GenericRequest::set_messege(::std::string&& value) {
  
  messege_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameWorkstore.AsyncNetworkEngine.GenericRequest.Messege)
}
#endif
inline void GenericRequest::set_messege(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  messege_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameWorkstore.AsyncNetworkEngine.GenericRequest.Messege)
}
inline void GenericRequest::set_messege(const char* value, size_t size) {
  
  messege_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameWorkstore.AsyncNetworkEngine.GenericRequest.Messege)
}
inline ::std::string* GenericRequest::mutable_messege() {
  
  // @@protoc_insertion_point(field_mutable:GameWorkstore.AsyncNetworkEngine.GenericRequest.Messege)
  return messege_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericRequest::release_messege() {
  // @@protoc_insertion_point(field_release:GameWorkstore.AsyncNetworkEngine.GenericRequest.Messege)
  
  return messege_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericRequest::set_allocated_messege(::std::string* messege) {
  if (messege != NULL) {
    
  } else {
    
  }
  messege_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), messege);
  // @@protoc_insertion_point(field_set_allocated:GameWorkstore.AsyncNetworkEngine.GenericRequest.Messege)
}

// -------------------------------------------------------------------

// GenericResponse

// string Messege = 2;
inline void GenericResponse::clear_messege() {
  messege_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericResponse::messege() const {
  // @@protoc_insertion_point(field_get:GameWorkstore.AsyncNetworkEngine.GenericResponse.Messege)
  return messege_.GetNoArena();
}
inline void GenericResponse::set_messege(const ::std::string& value) {
  
  messege_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameWorkstore.AsyncNetworkEngine.GenericResponse.Messege)
}
#if LANG_CXX11
inline void GenericResponse::set_messege(::std::string&& value) {
  
  messege_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameWorkstore.AsyncNetworkEngine.GenericResponse.Messege)
}
#endif
inline void GenericResponse::set_messege(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  messege_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameWorkstore.AsyncNetworkEngine.GenericResponse.Messege)
}
inline void GenericResponse::set_messege(const char* value, size_t size) {
  
  messege_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameWorkstore.AsyncNetworkEngine.GenericResponse.Messege)
}
inline ::std::string* GenericResponse::mutable_messege() {
  
  // @@protoc_insertion_point(field_mutable:GameWorkstore.AsyncNetworkEngine.GenericResponse.Messege)
  return messege_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericResponse::release_messege() {
  // @@protoc_insertion_point(field_release:GameWorkstore.AsyncNetworkEngine.GenericResponse.Messege)
  
  return messege_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericResponse::set_allocated_messege(::std::string* messege) {
  if (messege != NULL) {
    
  } else {
    
  }
  messege_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), messege);
  // @@protoc_insertion_point(field_set_allocated:GameWorkstore.AsyncNetworkEngine.GenericResponse.Messege)
}

// -------------------------------------------------------------------

// GenericErrorResponse

// string Error = 1;
inline void GenericErrorResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericErrorResponse::error() const {
  // @@protoc_insertion_point(field_get:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse.Error)
  return error_.GetNoArena();
}
inline void GenericErrorResponse::set_error(const ::std::string& value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse.Error)
}
#if LANG_CXX11
inline void GenericErrorResponse::set_error(::std::string&& value) {
  
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse.Error)
}
#endif
inline void GenericErrorResponse::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse.Error)
}
inline void GenericErrorResponse::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse.Error)
}
inline ::std::string* GenericErrorResponse::mutable_error() {
  
  // @@protoc_insertion_point(field_mutable:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse.Error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericErrorResponse::release_error() {
  // @@protoc_insertion_point(field_release:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse.Error)
  
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericErrorResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:GameWorkstore.AsyncNetworkEngine.GenericErrorResponse.Error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace AsyncNetworkEngine
}  // namespace GameWorkstore

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::GameWorkstore::AsyncNetworkEngine::Transmission> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_asyncrpc_2eproto__INCLUDED
