name: UPM Sync
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Config
        run: |
          git config --local user.email "contact@gameworkstore.com"
          git config --local user.name "game-workstore-bot"
      
      - name: Update README
        run: |
          if ! cmp --silent "README.md" "Assets/Package/README.md"; then
              echo "different"
              cp -f README.md Assets/Package/README.md
              git add --a
              git commit -m "Updated README.md"
              git push origin
          fi

      - name: Cook UPM
        run: |
          git subtree split -P Assets/Package/ -b upm
          git checkout upm
          ls

      - name: Push UPM
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: upm
          force: true

      - name: Cook Go Module
        run: |
          git checkout main
          git subtree split -P Assets/asyncnetworkengine -b go
          ls

      - name: Push GO Module
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: go
          force: true
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICEACCOUNT_KEY }}
          export_default_credentials: true